[package]
name = "aptmirs"
description = "A simple tool for mirroring apt/deb repositories"
authors = ["cyr"]
version = "0.20.1"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/cyr/aptmirs"
keywords = ["debian", "repository", "apt", "mirror"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.12"
async-channel = "2.5.0"
async-trait = "0.1.91"
bzip2 = "0.6.1"
clap = { version = "4.6.5", features = ["cargo", "derive", "env"] }
compact_str = { version = "0.9.1", features = ["serde"] }
console = "0.16.4"
flate2 = "1.1.9"
hex = "0.4.3"
indicatif = "0.18.6"
jiff = "0.2.35"
md5 = "0.8.1"
pathdiff = "0.2.3"
pgp = "0.19.0"
regex = "1.13.1"
reqwest = { version = "0.13.4" }
sha1 = "0.11.0"
sha2 = "0.11.0"
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "fs"] }
walkdir = "2.5.0"
xz2 = "0.1.7"

[profile.release]
codegen-units = 1
lto = "fat" 
strip = "symbols"
panic = "abort"
